# Generated by Django 6.0.5 on 2026-05-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_team_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='opt_in_state',
            field=models.CharField(choices=[('not_opted_in', 'Not Opted In'), ('opted_in_phone_unavailable', 'Opted In, Phone Unavailable'), ('opted_in_phone_available', 'Opted In, Phone Available')], default='not_opted_in', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='whatsapp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
