# Generated by Django 6.0.5 on 2026-05-11 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_conversation_custom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='opt_in_state',
        ),
    ]
