# Generated by Django 5.2 on 2026-05-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_opt_in_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'last_message_at'], name='conv_status_lastmsg_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['whatsapp_id'], name='conv_waid_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='msg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read', 'direction'], name='msg_unread_idx'),
        ),
    ]
