# Generated by Django 5.2.1 on 2026-05-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_seed_tulua_and_backfill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.RemoveField(
            model_name='conversationnote',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='conversationtag',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='conversationtake',
            name='is_active',
        ),
    ]
