# Generated by Django 5.2.1 on 2026-05-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('whatsapp_message_id__isnull', False)), fields=('whatsapp_message_id',), name='unique_whatsapp_message_id'),
        ),
    ]
