# Generated by Django 5.2.1 on 2026-06-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bot_exempt_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='resolved_by_bot',
            field=models.BooleanField(default=False),
        ),
    ]
