# Generated by Django 5.2.1 on 2026-06-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_conversation_resolved_by_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='BotSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['day_of_week', 'date'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('date__isnull', True), ('day_of_week__isnull', False)), models.Q(('date__isnull', False), ('day_of_week__isnull', True)), _connector='OR'), name='bot_schedule_exactly_one_of_day_or_date')],
            },
        ),
    ]
