# Generated by Django 5.2.1 on 2026-06-13 04:43

import datetime

from django.db import migrations


def seed_bot_config(apps, schema_editor):
    BotConfig = apps.get_model('api', 'BotConfig')
    BotSchedule = apps.get_model('api', 'BotSchedule')

    defaults = [
        ('faq_info_section',
         'SERVICIOS: Domicilios, Mensajería, Compras por encargo, Trámites, Bancarios, Domii Fijo (domiciliario dedicado por horas/días).\n'
         'HORARIOS: Lunes a sábado 8:00 AM a 8:00 PM, domingos y festivos 9:00 AM a 6:00 PM.\n'
         'COBERTURA: Tuluá urbano y veredas. Fuera del área (Cali, Buga) = tarifas fijas.\n'
         'PAGO: Efectivo (sin recargo) o Nequi (+$500). Pago al recibir.',
         'Texto informativo inyectado en el prompt del bot (servicios, horarios, cobertura, pago).'),
        ('outside_hours_reply',
         'Gracias por escribirnos. Actualmente estamos fuera de nuestro horario de atención. '
         'Te responderemos en cuanto estemos disponibles. ¡Gracias por tu paciencia!',
         'Respuesta automática cuando el bot recibe un mensaje fuera del horario de atención.'),
        ('llm_temperature', 0.25, 'Temperatura del modelo LLM (0.0–2.0).'),
        ('llm_max_tokens', 1024, 'Máximo de tokens de salida del LLM por respuesta.'),
        ('llm_retry_count', 3, 'Número de reintentos ante fallo de API del LLM.'),
        ('tools_cache_ttl', 300, 'TTL en segundos del caché de herramientas de la calculadora.'),
        ('max_user_message_length', 1000, 'Longitud máxima de caracteres del mensaje del usuario.'),
        ('state_machine_enabled', False, 'Habilitar la máquina de estados del bot en lugar del flujo LLM clásico.'),
        ('allowed_url_domains', [], 'Dominios de URL adicionales permitidos en respuestas del bot.'),
    ]

    for key, value, description in defaults:
        BotConfig.objects.get_or_create(
            key=key,
            defaults={'value': value, 'description': description},
        )

    t = datetime.time
    default_schedule = [
        (0, None, t(8, 0), t(20, 0), True, 'Lunes'),
        (1, None, t(8, 0), t(20, 0), True, 'Martes'),
        (2, None, t(8, 0), t(20, 0), True, 'Miércoles'),
        (3, None, t(8, 0), t(20, 0), True, 'Jueves'),
        (4, None, t(8, 0), t(20, 0), True, 'Viernes'),
        (5, None, t(8, 0), t(20, 0), True, 'Sábado'),
        (6, None, t(9, 0), t(18, 0), True, 'Domingo'),
    ]
    for day_of_week, date, open_time, close_time, active, label in default_schedule:
        BotSchedule.objects.get_or_create(
            day_of_week=day_of_week,
            defaults={
                'open_time': open_time,
                'close_time': close_time,
                'is_active': active,
                'label': label,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_botconfig_botschedule'),
    ]

    operations = [
        migrations.RunPython(seed_bot_config, migrations.RunPython.noop),
    ]
