# Generated by Django 5.2.1 on 2026-06-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_seed_bot_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botschedule',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo y Festivos')], null=True),
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('language', models.CharField(default='es', max_length=10)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], default='MARKETING', max_length=20)),
                ('template_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled'), ('FLAGGED', 'Flagged'), ('PENDING_DELETION', 'Pending Deletion'), ('DELETED', 'Deleted'), ('ARCHIVED', 'Archived'), ('UNARCHIVED', 'Unarchived'), ('IN_APPEAL', 'In Appeal'), ('LIMIT_EXCEEDED', 'Limit Exceeded'), ('LOCKED', 'Locked'), ('REINSTATED', 'Reinstated')], default='PENDING', max_length=30)),
                ('quality_score', models.CharField(blank=True, choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('components', models.JSONField(default=list)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'language')},
            },
        ),
    ]
