# Generated by Django 5.2.1 on 2026-07-04 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_whatsapp_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('connected', 'Connected'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('missed', 'Missed')], default='pending', max_length=30)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('recipient_bsuid', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('biz_opaque_callback_data', models.CharField(blank=True, max_length=512, null=True)),
                ('deeplink_payload', models.CharField(blank=True, max_length=1024, null=True)),
                ('cta_payload', models.CharField(blank=True, max_length=1024, null=True)),
                ('recording_status', models.CharField(blank=True, max_length=20, null=True)),
                ('recording_purpose', models.CharField(blank=True, max_length=250, null=True)),
                ('recording_announcement_language', models.CharField(blank=True, max_length=20, null=True)),
                ('recording_audio_id', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_audio_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('recording_audio_sha256', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_audio_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sdp_offer', models.TextField(blank=True, null=True)),
                ('sdp_answer', models.TextField(blank=True, null=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='api.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='api_call_convers_4b6ce7_idx')],
            },
        ),
    ]
