# Generated by Django 5.2.1 on 2026-07-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_call_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='recording_local_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
