# Generated by Django 5.2.1 on 2026-07-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_seed_call_recording_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-is_pinned', 'pinned_at', '-last_message_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_pinned', 'pinned_at'], name='conv_pin_idx'),
        ),
    ]
