# Generated by Django 5.2.1 on 2026-07-05 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_search_vector_populate_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationtake',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='ConversationUserPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pins', to='api.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned_at'],
                'indexes': [models.Index(fields=['user', 'conversation'], name='api_convers_user_id_2a9818_idx')],
                'unique_together': {('conversation', 'user')},
            },
        ),
    ]
