# Generated by Django 5.2.1 on 2026-07-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_agent_take_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerasset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
