# Generated by Django 5.2.1 on 2026-07-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_sticker_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='botschedule',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='If True, this block is non-working (break/closure)'),
        ),
    ]
