# Generated by Django 5.2.1 on 2026-07-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_botschedule_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_frequently_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
