# Generated by Django 5.2.1 on 2026-07-15 14:17

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_message_is_forwarded_message_is_frequently_forwarded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('tags', models.JSONField(default=list)),
                ('usage_count', models.PositiveIntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Suggestion',
                'verbose_name_plural': 'Message Suggestions',
                'ordering': ['-last_used'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['text'], name='msg_suggestion_text_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
