# Generated by Django 5.2.1 on 2026-09-19 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_template_exclusion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botexemptcontact',
            name='ops_courier_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='botexemptcontact',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ops_sync', 'Sincronizado')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ops_client_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ops_client_match_source',
            field=models.CharField(blank=True, choices=[('auto_phone', 'Auto (teléfono)'), ('manual', 'Manual'), ('order', 'Pedido')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ops_client_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ops_client_user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='IntegrationApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(max_length=12)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration API Key',
                'verbose_name_plural': 'Integration API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ops_batch_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('ops_client_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('origin_address', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(blank=True, default='', max_length=20)),
                ('profile', models.CharField(blank=True, default='', max_length=20)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('acompanante', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Enviando'), ('failed', 'Fallido'), ('disponible', 'Buscando domiciliario'), ('asignado', 'Asignado'), ('confirmado', 'Confirmado'), ('en_ruta', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='draft', max_length=20)),
                ('notified_statuses', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='agent', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_no', models.PositiveSmallIntegerField(default=1)),
                ('ops_order_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('service_type', models.CharField(max_length=40)),
                ('dest_address', models.TextField(blank=True, default='')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('observation', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.order')),
            ],
            options={
                'verbose_name': 'Order Stop',
                'verbose_name_plural': 'Order Stops',
                'ordering': ['stop_no', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['conversation', 'status'], name='order_conv_status_idx'),
        ),
    ]
