# Generated by Django 5.2.1 on 2026-09-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_order_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('take', 'Take'), ('release', 'Release'), ('pin', 'Pin'), ('unpin', 'Unpin'), ('send_message', 'Send Message'), ('delete_conversation', 'Delete Conversation'), ('toggle_status', 'Toggle Status'), ('link_client', 'Link Client'), ('unlink_client', 'Unlink Client')], max_length=32),
        ),
    ]
