"""Input and output sanitization for the bot.

*Inbound guard* — strips known prompt-injection patterns from user
messages before the LLM sees them.

*Outbound guard* — filters LLM output to block unsafe URLs and
profanity before sending to WhatsApp.
"""

from __future__ import annotations

import logging
import re

from .config import get_max_user_message_length, get_allowed_url_domains

logger = logging.getLogger("api.bot.guard")

# ---------------------------------------------------------------------------
#  Inbound — user → LLM
# ---------------------------------------------------------------------------

# Patterns whose mere presence flags a message as an injection attempt.
_INJECTION_PATTERNS: list[re.Pattern] = [
    re.compile(p, re.I | re.MULTILINE)
    for p in
    [
        # Spanish & English instruction overrides (handle start-of-string too)
        r"(?:^|\s)ignora\s+todas?\s+(las\s+)?instrucciones?\s+(anteriores|previas)?\s*",
        r"(?:^|\s)ignore\s+all\s+(previous|prior|above)\s+instructions?\s*",
        r"(?:^|\s)ahora\s+eres?\s+",
        r"(?:^|\s)you\s+are\s+now\s+",
        r"(?:^|\s)act[uú]as?\s+como\s+",
        r"(?:^|\s)act\s+as\s+",
        r"(?:^|\s)finge\s+(que|ser)\s+",
        r"(?:^|\s)pretend\s+(you\s+are|to\s+be)\s+",
        r"(?:^|\s)[aá]brete?\s+",
        # System prompt extraction
        r"(?:^|\s)tu\s+(prompt|sistema|instrucci[oó]n)\s*",
        r"(?:^|\s)your\s+(prompt|system|instructions?)\s*",
        r"\[system\]",
        r"<system>",
        r"\{\{\{",
        # Role-play / jailbreak
        r"(?:^|\s)roleplay\s+",
        r"(?:^|\s)juego\s+de\s+rol\s+",
        r"(?:^|\s)DAN\s+",
        r"(?:^|\s)developer\s+mode\s+",
        # Safety filter bypass
        r"(?:^|\s)[ou]lvid(a|e|ar)\s+(todo|lo\s+anterior)\s*",
        r"(?:^|\s)forget\s+(everything|all\s+prior)\s*",
        r"nuevas?\s+instrucciones?",
        r"new\s+instructions?",
        r"(?:^|\s)reset\s+",
        r"(?:^|\s)restart\s+",
    ]
]

# Lines that should be stripped entirely if they appear (email-style quoting)
_STRIP_LINE_PATTERNS: list[re.Pattern] = [
    re.compile(r"^>.*$", re.MULTILINE),
]


def sanitize_user_input(text: str | None) -> str | None:
    """Sanitize *text* before sending to the LLM.

    Returns ``None`` if the message should be skipped entirely
    (empty, all-whitespace, or fully filtered).
    Returns the sanitized string otherwise.
    """
    if not text or not text.strip():
        return None

    max_len = get_max_user_message_length()
    text = text[:max_len]

    # Strip control characters (keep \n \r \t)
    text = "".join(ch for ch in text if ord(ch) >= 32 or ch in "\n\r\t")
    text = text.strip()

    if not text:
        return None

    # Remove email-style quote lines
    for pat in _STRIP_LINE_PATTERNS:
        text = pat.sub("", text)

    text = text.strip()
    if not text:
        return None

    # Check for injection patterns
    for pat in _INJECTION_PATTERNS:
        if pat.search(text):
            logger.warning("Injection pattern matched: %s", pat.pattern[:60])
            return "[mensaje filtrado]"

    return text


# ---------------------------------------------------------------------------
#  Outbound — LLM → WhatsApp
# ---------------------------------------------------------------------------

# Spanish profanity — replace matched tokens with asterisks
_PROFANITY_PATTERNS: list[re.Pattern] = [
    re.compile(r"\b" + p + r"\b", re.I)
    for p in [
        "carajo",
        "mierda",
        "put[ao]",
        "pendej[ao]",
        "hij[ae]puta",
        "coger",
        "cojones",
        "maric[oó]n",
        "cabr[oó]n",
        "web[oó]n",
        "culiao",
        "conchetumadre",
        "ctm",
        "lptm",
        "maldit[ao]",
        "imbecil",
        "est[úu]pid[ao]",
        "tonto",
        "tarad[ao]",
        "idiota",
        "subnormal",
        "mongol[oi]c[oó]",
    ]
]

_PROFANITY_REPLACEMENT = "***"

# URL detection
_URL_PATTERN = re.compile(r"https?://\S+", re.I)

# Default allowed domains for URLs generated by the LLM (business domains)
_DEFAULT_ALLOWED_DOMAINS = frozenset({"wa.me", "facebook.com", "whatsapp.com"})


def _get_allowed_domains() -> frozenset[str]:
    custom = get_allowed_url_domains()
    if custom:
        return _DEFAULT_ALLOWED_DOMAINS | frozenset(
            d.lower().strip() for d in custom if d.strip()
        )
    return _DEFAULT_ALLOWED_DOMAINS

_SAFE_FALLBACK = (
    "Lo siento, no puedo procesar esa respuesta. "
    "\xbfHay algo m\xe1s en lo que pueda ayudarte?"
)


def sanitize_llm_output(text: str | None) -> str:
    """Sanitize LLM output before sending to WhatsApp.

    Strips profanity, blocks unknown URLs, and returns a safe fallback
    if the result is empty.
    """
    if not text or not text.strip():
        return _SAFE_FALLBACK

    # Strip control characters
    text = "".join(ch for ch in text if ord(ch) >= 32 or ch in "\n\r\t")

    # Block non-allowed URLs
    allowed = _get_allowed_domains()

    def _replace_url(m: re.Match) -> str:
        url = m.group(0).lower()
        # Extract domain
        domain_match = re.search(r"https?://([^/?#]+)", url)
        if domain_match:
            domain = domain_match.group(1).lower()
            # Remove www. prefix for matching
            if domain.startswith("www."):
                domain = domain[4:]
            if domain in allowed:
                return m.group(0)  # pass through
        return "[enlace no permitido]"

    text = _URL_PATTERN.sub(_replace_url, text)

    # Replace profanity
    for pat in _PROFANITY_PATTERNS:
        text = pat.sub(_PROFANITY_REPLACEMENT, text)

    text = text.strip()
    if not text:
        return _SAFE_FALLBACK

    return text
